# This file was generated by GoReleaser. DO NOT EDIT.
cask "repoidx" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "98c58214610ac3235769a4ce53ab58c1ccb2cd53a3e73aafe6ee4731d9f84763"
      url "https://github.com/jverhoeks/repoidx/releases/download/v#{version}/repoidx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "41b429aa8382a8b39e54e9c920af0e613af2a16db440986e3ab3a95656a63c16"
      url "https://github.com/jverhoeks/repoidx/releases/download/v#{version}/repoidx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b0c30017ff88aaaf67fb23b12043a9c4fa16acfa8995b140afe6b4ab6cb0648"
      url "https://github.com/jverhoeks/repoidx/releases/download/v#{version}/repoidx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "639e2bcf671c736465447a8db7e7ffc22541f8a77f5797c418d9a9ea89c1b615"
      url "https://github.com/jverhoeks/repoidx/releases/download/v#{version}/repoidx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repoidx"
  desc "Index, search and inspect every git repository on your machine"
  homepage "https://github.com/jverhoeks/repoidx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "repoidx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repoidx"]
    end
  end

  # No zap stanza required
end
